//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UcusTakipEntities : DbContext
    {
        public UcusTakipEntities()
            : base("name=UcusTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HarekatSB_Komutan> HarekatSB_Komutan { get; set; }
        public virtual DbSet<HavaAracları> HavaAracları { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Kur> Kurs { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<PersonelAracYetki> PersonelAracYetkis { get; set; }
        public virtual DbSet<PersonelKomutanı> PersonelKomutanı { get; set; }
        public virtual DbSet<PersonelKur> PersonelKurs { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Tarih> Tarihs { get; set; }
        public virtual DbSet<UcusBilgileri> UcusBilgileris { get; set; }
    }
}
