//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelKur
    {
        public int PersonelKursID { get; set; }
        public Nullable<int> PersonelNo { get; set; }
        public Nullable<int> KursNo { get; set; }
        public Nullable<System.DateTime> KursTarihi { get; set; }
    
        public virtual Kur Kur { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
