//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelAracYetki
    {
        public int PersonelAracYetkiID { get; set; }
        public Nullable<int> HavaAraciNo { get; set; }
        public Nullable<int> PersonelNo { get; set; }
        public Nullable<bool> YetkisiVar { get; set; }
        public Nullable<int> AracToplamUcusSuresi { get; set; }
    
        public virtual HavaAracları HavaAracları { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
