//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Kullanicis = new HashSet<Kullanici>();
            this.PersonelAracYetkis = new HashSet<PersonelAracYetki>();
            this.PersonelKomutanı = new HashSet<PersonelKomutanı>();
            this.PersonelKurs = new HashSet<PersonelKur>();
            this.Tarihs = new HashSet<Tarih>();
            this.UcusBilgileris = new HashSet<UcusBilgileri>();
        }
    
        public int PersonelNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string SinifRutbesi { get; set; }
        public Nullable<int> SicilNo { get; set; }
        public Nullable<int> BroveNo { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Birligi { get; set; }
        public string UcusBirligi { get; set; }
        public Nullable<System.DateTime> IlkUcusTarihi { get; set; }
        public Nullable<System.DateTime> TemelKursBitirmeTarihi { get; set; }
        public Nullable<int> ToplamUcusYılı { get; set; }
        public string GorevDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelAracYetki> PersonelAracYetkis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelKomutanı> PersonelKomutanı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelKur> PersonelKurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarih> Tarihs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcusBilgileri> UcusBilgileris { get; set; }
    }
}
