//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelKomutanı
    {
        public int PersonelKomutanıID { get; set; }
        public Nullable<int> PersonelNo { get; set; }
        public Nullable<int> KisiID { get; set; }
        public Nullable<System.DateTime> PKTarih { get; set; }
        public string KisiAciklamasi { get; set; }
    
        public virtual HarekatSB_Komutan HarekatSB_Komutan { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
