//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarih
    {
        public int TarihID { get; set; }
        public int PersonelNo { get; set; }
        public Nullable<System.DateTime> UcakStanSonTarihi { get; set; }
        public Nullable<System.DateTime> HeliStanSonTarih { get; set; }
        public Nullable<System.DateTime> YillikSaglik { get; set; }
        public Nullable<System.DateTime> YillikSaglikSon { get; set; }
        public Nullable<System.DateTime> BesYillikSaglik { get; set; }
        public Nullable<System.DateTime> BesYillikSaglikSon { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
