//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemAnalizi_GorselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcusBilgileri
    {
        public int UcusNo { get; set; }
        public int PersonelNo { get; set; }
        public int HavaAraciNo { get; set; }
        public Nullable<System.DateTime> UcusTarihi { get; set; }
        public string UcusTipi { get; set; }
        public Nullable<int> UcusDakikası { get; set; }
    
        public virtual HavaAracları HavaAracları { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
